# Copyright (c) 2016-2019 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: DockSTARTer Wiki
site_description: Guides for Docker
site_author: Eric N, Matt D, Ryan K
site_url: https://wiki.dockstarter.com/

# Repository
repo_name: GhostWriters/DockSTARTer-wiki
repo_url: https://github.com/GhostWriters/DockSTARTer-wiki
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2019 GhostWriters'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Customization
extra:
  social:
    - type: globe
      link: http://dockstarter.com
    - type: github-alt
      link: https://github.com/GhostWriters/dockstarter

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - General:
    - FAQ: general/Frequently-Asked-Questions.md
    - Migration: general/Migration.md
    - SMB-Mounting: general/SMB-Mounting.md
    - VPN Information: general/VPN-Information.md
  - Application Specifics:
    - AirDCpp: application specifics/AirDCpp.md
    - ddclient: application specifics/ddclient.md
    - DelugeVPN: application specifics/DelugeVPN.md
    - Duplicati: application specifics/Duplicati.md
    - Home-Assistant: application specifics/Home-Assistant.md
    - Let's Encrypt-(Cerbot): application specifics/Lets-Encrypt-Certbot.md
    - Logarr: application specifics/Logarr.md
    - Netdata: application specifics/Netdata.md
    - NextCloud: application specifics/NextCloud.md
    - Ouroboros: application specifics/Ouroboros.md
    - Pi-hole: application specifics/Pi-hole.md
    - Portainer: application specifics/Portainer.md
    - Samba: application specifics/Samba.md
    - Watchtower: application specifics/Watchtower.md
  - Other Pages:
    - Advanced Usage: other pages/Advanced-Usage.md
    - Available Applications: other pages/Available-Applications.md
    - Backups: other pages/Backups.md
    - Overrides: other pages/Overrides.md
    - Setting Up a Domain: other pages/Setting-Up-a-Domain.md
    - Techical Information: other pages/Technical-Info
  - Discord: specimen.md


# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
