# Project information
site_name: 'DockSTARTer'
site_description: 'DockSTARTer helps you get started with home server apps running in Docker.'
site_author: 'GhostWriters'
site_url: 'https://dockstarter.com'

# Repository
repo_name: 'GhostWriters/DockSTARTer'
repo_url: 'https://github.com/GhostWriters/DockSTARTer'
edit_uri: 'edit/docs/docs/'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 GhostWriters'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'img/icon.png'
  favicon: 'img/favicon.ico'

# Navigation
nav:
  - Home: index.md
  - Basics:
    - Getting Started (Video): https://www.youtube.com/watch?v=6pkbS07CAnU
    - Available Applications: basics/available-apps.md
    - How to Migrate to DS: basics/migration.md
    - Frequently Asked Questions: basics/faq.md
    - Port Conflicts: basics/port-conflicts.md
  - App Specifics:
    - AirDCpp: apps/airdcpp.md
    - BitWarden: apps/bitwarden.md
    - ddclient: apps/ddclient.md
    - DelugeVPN: apps/delugevpn.md
    - Duplicati: apps/duplicati.md
    - Home Assistant: apps/homeassistant.md
    - Jackett: apps/jackett.md
    - Let's Encrypt (Certbot): apps/letsencrypt.md
    - Logarr: apps/logarr.md
    - Netdata: apps/netdata.md
    - NextCloud: apps/nextcloud.md
    - OpenVPN-AS: apps/openvpnas.md
    - Ouroboros: apps/ouroboros.md
    - Pi-hole: apps/pihole.md
    - Plex: apps/plex.md
    - Portainer: apps/portainer.md
    - Samba: apps/samba.md
    - Watchtower: apps/watchtower.md
  - Advanced:
    - Advanced Usage: advanced/advanced-usage.md
    - Backups: advanced/backups.md
    - Overrides: advanced/overrides.md
    - Setting Up a Domain: advanced/domain-info.md
    - SMB Mounting: advanced/smb-mounting.md
    - Technical Info: advanced/technical-info.md
    - VPN Information: advanced/vpn-info.md
    - Uninstall: advanced/uninstall.md
